export enum Category {
  SuperMarket = 'supermarket',
  DeliveryProducts = 'delivery-products',
  Clothes = 'clothes',
  Cosmetics = 'cosmetics',
  Cat = 'cat',
  HouseholdGoods = 'household-goods',
  Travel = 'travel',
  Pharmacy = 'pharmacy',
  HairStyle = 'hair-style',
  Alcohol = 'alcohol',
  Snus = 'snus',
  Education = 'education',
  Water = 'water',
  Beverages = 'beverages',
  Snacks = 'snacks',
  Other = 'other',
}
